### ISSUE TITLE
Deploy from windows

### ISSUE THREAD

**Issue by dmitry-yackevich** [onthebeach/capistrano-slackify#22]
Hi guys,
When i'm deploy from mac everything OK, but from Windows:

cap aborted!
NoMethodError: undefined method `name' for nil:NilClass

Tasks: TOP => deploy:starting => slack:notify_started
(See full trace by running task with --trace)
The deploy has failed with an error: undefined method `name' for nil:NilClass
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sshkit-1.7.1/lib/sshkit/host.rb:29:in`initialize': undefined method `name' for nil:NilClass (NoMethodError)
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sshkit-1.7.1/lib/sshkit/backends/local.rb:10:in`new'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sshkit-1.7.1/lib/sshkit/backends/local.rb:10:in `initialize'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/capistrano-3.4.0/lib/capistrano/dsl.rb:59:in`new'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/capistrano-3.4.0/lib/capistrano/dsl.rb:59:in `run_locally'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/capistrano-slackify-2.2.0/lib/capistrano/tasks/slackify.cap:31:in`block (2 levels) in <top (required)>'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in`block in execute'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in`execute'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
       from C:/Ruby193/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:165:in`invoke'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/capistrano-3.4.0/lib/capistrano/dsl/task_enhancements.rb:14:in `block in after'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in`call'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in`each'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:179:in`block in invoke_with_call_chain'
       from C:/Ruby193/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in`invoke_with_call_chain'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/capistrano-3.4.0/lib/capistrano/dsl.rb:16:in`invoke'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/capistrano-3.4.0/lib/capistrano/dsl/task_enhancements.rb:57:in `exit_deploy_because_of_exception'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/capistrano-3.4.0/lib/capistrano/application.rb:78:in`exit_because_of_exception'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:186:in `rescue in standard_exception_handling'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in`standard_exception_handling'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/capistrano-3.4.0/lib/capistrano/application.rb:15:in`run'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/capistrano-3.4.0/bin/cap:3:in `<top (required)>'
       from C:/Ruby193/bin/cap:23:in`load'
       from C:/Ruby193/bin/cap:23:in `<main>'

**Comment by seenmyfate** [comment]
It seems that [`run_locally` (as provided by `SSHKit`) isn't supported on Windows](https://github.com/capistrano/sshkit/issues/252) - this is due to using the `Etc` module to determine the user when running `execute`.  

We should be able to find a way around this, I'll look into it

**Comment by leehambley** [comment]
@seenmyfate happy to take a patch as you know - The obvious fix would be to use `$USER` which might be available on Windows, or a better fix to prefer `Etc`.

**Comment by seenmyfate** [comment]
Thanks for that @leehambley, I'll try that angle

**Comment by slavajacobson** [comment]
Any luck with this?

**Comment by rfair404** [comment]
Wondering what the status is on this. I'm able to deploy just fine on my mac and linux boxes, but on Windows I get a message 
```The deploy has failed with an error: No such file or directory - /mingw64/bin/curl -X POST --data-urlencode ```
Capistrano seems to be cheerful, as I can run my deployment without the slackify enabled :(

**Comment by ezekg** [comment]
@rfair404, your error is because you don't have [`curl`](https://curl.haxx.se/download.html) installed, which is what [this library uses to `POST` to Slack's API](https://github.com/onthebeach/capistrano-slackify/blob/master/lib/capistrano/tasks/slackify.cap?ts=2#L11-L14). You should be able to fix that error by downloading `curl` from the link above (near the bottom of the page for Windows). You'll probably still hit the other issues in this thread, though.

**Comment by seenmyfate** [comment]
@rfair404 thanks for the reminder, all being well I will take another look at this on Friday

**Comment by rfair404** [comment]
I thought that was the case too, but as it turns out, curl IS installed.
when I do "which curl" i get the path to curl. I also tried to add it to
the sshkit.config to no avail.


On Wed, Feb 17, 2016 at 3:36 PM, Tom Clements <notifications@github.com>
wrote:

> @rfair404 <https://github.com/rfair404> thanks for the reminder, all
> being well I will take another look at this on Friday
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/onthebeach/capistrano-slackify/issues/22#issuecomment-185392694>
> .
>



-- 
Thanks,

Russell Fair
770.401.9039

**Comment by seenmyfate** [comment]
@dmitry-yackevich @slavajacobson this issue should have been resolved by [this change](https://github.com/capistrano/sshkit/pull/293) which was included in the 1.8.0 release, please let me know if you're still having issues after updating.
