### ISSUE TITLE
Send notify on more channels

### ISSUE THREAD

**Issue by JellyBellyDev** [onthebeach/capistrano-slackify#32]
Is it possible to send the notification on multiple channels? Yes? how?
I tried to set
`set :slack_channel, '#bot-all,#product-bot'`
or
`set :slack_channel, '#bot-all #product-bot'`
but not work!

thank you

**Comment by seenmyfate** [comment]
@JellyBellyDev I'm not entirely sure that Slack's API supports sending a message to more than one channel, although it could probably be implemented by sending separate requests per channel.  Happy to accept a PR if you have time to put one together?

**Comment by JellyBellyDev** [comment]
Sorry but ruby it's not in my confort zone! :D

**Comment by seenmyfate** [comment]
Ok no problem, thanks for the suggestion and I will try to take a look at this when I've got some time 👍

**Comment by Scuottolinx** [comment]
i have added PR for this issue #33

**Comment by seenmyfate** [comment]
Closed by #33
