### ISSUE TITLE
slack_parse should be none

### ISSUE THREAD

**Issue by likeuwill** [onthebeach/capistrano-slackify#36]
Please change slack_parse default value. It's should be 'none' or 'all', slack can't parse 'default' value.

**Comment by Deanoo94** [comment]
Hi @likeuwill thanks for reporting the issue, we'll look into this.

**Comment by seenmyfate** [comment]
This is now available in [v2.10.2](https://rubygems.org/gems/capistrano-slackify/versions/2.10.2)
